# Generated by Django 5.2.1 on 2025-06-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "message_api",
            "0002_calendarevent_message_alter_timelineevent_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarevent",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
    ]
